[build]
  base = ""               # Optional if base dir is already set in Netlify UI
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200